spring:
  profiles:
    include: real,real-private,oauth,payment
#    include: dev,dev-private,oauth
  # 이미지 파일 크기 제한
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# AWS S3를 연동한 프로젝트에서 발생하는 오류 방지
# 프로젝트 배포시 기본으로 CloudFormation 구성을 시작하기 때문에
# 설정한 CloudFormation이 없으면 프로젝트 실행이 되지 않음.
# 해당 기능을 사용하지 않도록 false로 설정.
cloud:
  aws:
    stack:
      auto: false