server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://sigma-db.cplnqa02qixm.ap-northeast-2.rds.amazonaws.com:3306/sigmadb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      format_sql: auto
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
  config:
    activate:
      on-profile: real
  sql:
    init:
      mode: never
