payments:
  toss:
    origin_url: https://api.tosspayments.com/v1
    test_client_api_key: test_ck_jkYG57Eba3G06EgN4PwVpWDOxmA1
    test_secret_api_key: test_sk_7DLJOpm5QrlJOa1YxMN3PNdxbWnY
    live_client_api_key:
    live_secret_api_key:
    success_url: http://13.125.39.167:9090/v1/api/payment/success
    fail_url: http://13.125.39.167:9090/v1/api/payment/fail
    virtual_success_url: http://13.125.39.167:9090/v1/api/payment/virtual/success
    virtual_fail_url: http://13.125.39.167:9090/v1/api/payment/virtual/fail