spring:
  datasource:
    username: admin
    password: inspiration1!
email:
  id: sigma.idea.insight@gmail.com
  password: mqjufrgcxyapwatd

cloud:
  aws:
    credentials:
      access-key: AKIAYXYDFRXMYWQHVYBK
      secret-key: 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
    region:
      static: ap-northeast-2

aws:
  bucket:
    name: sigma-image-bucket
    url: https://sigma-image-bucket.s3.ap-northeast-2.amazonaws.com